title: Wazuh index patterns and OSSEM field mappings
order: 20
backends:
  - elastalert
  - elastalert-dsl
logsources:
  windows-application:
    product: windows
    service: application
    index: wazuh-alerts-*
  windows-security:
    product: windows
    service: security
    index: wazuh-alerts-*
  windows-sysmon:
    product: windows
    service: sysmon
    index: wazuh-alerts-*
  windows-system:
    product: windows
    service: system
    index: wazuh-alerts-*
  windows-wmi:
    product: windows
    service: wmi
    index: wazuh-alerts-*
  windows-powershell:
    product: windows
    service: powershell
    index: wazuh-alerts-*
  windows-powershell-classic:
    product: windows
    service: powershell-classic
    index: wazuh-alerts-*
defaultindex: wazuh-alerts-*
fieldmappings:
    AccessMask: data.win.eventdata.accessMask
    AccountName: data.win.eventdata.accountName
    AllowedToDelegateTo: user_attribute_allowed_todelegate
    AttributeLDAPDisplayName: dsobject_attribute_name
    AuditPolicyChanges: policy_changes
    AuthenticationPackageName: logon_authentication_package
    CallingProcessName: process_path
    CallTrace: data.win.eventdata.callTrace
    ClientAddress: data.win.eventdata.clientAddress
    ClientIPAddress: data.win.eventdata.clientIPAddress
    ClientIP: data.win.eventdata.clientIPAddress
    CommandLine: data.win.eventdata.commandLine
    Company: data.win.eventdata.company
    ComputerName: data.win.system.computer
    Configuration:
        EventID=16: sysmon_configuration
    ConnectedViaIPAddress: dst_nat_ip_addr
    CurrentDirectory: data.win.eventdata.currentDirectory
    Description: data.win.eventdata.description
    DestAddress: data.win.eventdata.destAddress
    Destination:
        EventID=20: wmi_consumer_destination
    DestinationHostname: data.win.eventdata.destinationHostname
    DestinationIp: data.win.eventdata.destinationIp
    DestinationPort: data.win.eventdata.destinationPort
    DestinationPortName: data.win.eventdata.destinationPortName
    Details:
        EventID=13: data.win.eventdata.details
    Device: data.win.eventdata.deviceName
    EngineVersion: data.win.eventdata.engine Version
    EventID: data.win.system.eventID
    EventType: data.win.eventdata.eventType
    EventNamespace:
        EventID=19: wmi_namespace
    Filter:
        EventID=21: wmi_filter_path
    FailureCode: ticket_failure_code
    FileName: data.win.eventdata.originalFileName
    FileVersion: data.win.eventdata.fileVersion
    GrantedAccess: data.win.eventdata.grantedAccess
    GroupName: group_name
    GroupSid: group_sid
    HiveName: hive_name
    HostVersion: powershell.host.version
    Image: data.win.eventdata.image
    ImageLoaded:
        EventID=6: data.win.eventdata.imageLoaded
        EventID=7: data.win.eventdata.imageLoaded
    Imphash: hash_imphash
    Initiated:
        EventID=3: data.win.eventdata.initiated
    IntegrityLevel:
        EventID=1: data.win.eventdata.integrityLevel
    ipAddress: dst_ip_addr
    IpAddress: src_ip_addr
    IPString: src_ip_addr
    LaunchedViaIPAddress: dst_ip_addr
    LogonProcessName: data.win.eventdata.logonProcessName
    LogonType: data.win.eventdata.logonType
    LogonId: data.win.eventdata.logonId
    Message: data.win.system.message
    MachineIpAddress: dst_ip_addr
    MachineName: host_name
    Name:
        EventID=19: wmi_name
        EventID=20: wmi_name
    NewProcessName: process_path
    NewName:
        EventID=14: registry_key_new_name
    ObjectClass: dsobject_class
    ObjectName: data.win.eventdata.objectName
    ObjectType: data.win.eventdata.objectType
    ObjectValueName: object_value_name
    Operation:
        EventID=19: wmi_operation
        EventID=20: wmi_operation
        EventID=21: wmi_operation
    OperationType: data.win.eventdata.operationType
    OriginalFileName: data.win.eventdata.originalFileName
    ParentImage: data.win.eventdata.parentImage
    ParentProcessName: data.win.eventdata.parentImage
    PasswordLastSet: data.win.eventdata.passwordLastSet
    Path: data.win.eventdata.image
    ParentCommandLine: data.win.eventdata.parentCommandLine
    PipeName: data.win.eventdata.pipeName
    ProcessName: data.win.eventdata.processName
    ProcessCommandLine: process_command_line
    Product: data.win.eventdata.product
    Properties: data.win.eventdata.properties
    Protocol:
        EventID=3: network_protocol
    Query:
        EventID=19: wmi_query
    RelativeTargetName: data.win.eventdata.relativeTargetName
    SourceAddress: src_ip_addr
    SchemaVersion:
        EventID=4: sysmon_schema_version
    ServiceFileName: data.win.eventdata.imagePath
    ServiceName: data.win.eventdata.serviceName
    ShareName: data.win.eventdata.shareName
    Signature: data.win.eventdata.signature
    SignatureStatus: data.win.eventdata.signatureStatus
    Signed: data.win.eventdata.signed
    Source: data.win.eventdata.source Name
    SourceHostname: data.win.eventdata.sourceHostname
    SourceImage: data.win.eventdata.sourceImage
    SourceIp: data.win.eventdata.sourceIp
    SourcePort: data.win.eventdata.sourcePort
    SourcePortName: data.win.eventdata.sourcePortName
    StartAddress: thread_start_address
    StartFunction: thread_start_function
    StartModule: thread_start_module
    Status: event_status
    State:
        EventID=4: service_state
        EventID=16: sysmon_configuration_state
    SubjectUserName:
        EventID=4624: user_reporter_name
        EventId=4648: user_name
        EventID=5140: user_name
    TargetServer: dst_ip_addr
    TaskName: task_name
    TicketEncryptionType: ticket_encryption_type
    TicketOptions: ticket_options
    TargetFilename: data.win.eventdata.targetFilename
    TargetImage: data.win.eventdata.targetImage
    TargetProcessAddress: thread_start_address
    TargetObject: data.win.eventdata.targetObject
    Type:
        EventID=20: wmi_consumer_type
    User: data.win.eventdata.user
    UserName: user_name
    Value:
      EventID=1102: dst_ip_addr
    Version:
        EventID=4: sysmon_version
    Workstation: data.win.eventdata.sourceHostname
    WorkstationName: data.win.eventdata.sourceHostname
